swagger: '2.0'
info: {title: XMLtoJSON, description: Converting XML string to JSON, version: '1.0'}
host: example.net
basePath: /
schemes: [https]
consumes: []
produces: []
paths:
  /:
    post:
      responses:
        default:
          description: default
          schema:
            type: object
            properties: {}
      summary: XMLtoJSON
      description: Converting XML string to JSON
      operationId: XMLtoJSON
      x-ms-visibility: important
      parameters:
      - name: body
        in: body
        required: false
        schema:
          type: object
          properties:
            xml: {type: string, description: xml}
definitions: {}
parameters: {}
responses: {}
securityDefinitions: {}
security: []
tags: []
